services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: cantinacf-nginx
    restart: unless-stopped
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_data:/var/log/nginx
      - ./cert.crt:/etc/nginx/ssl/cert.crt
      - ./cert.key:/etc/nginx/ssl/cert.key
    depends_on:
      - cantinacf-frontend
    networks:
      - cantinacf

  cantinacf-backend:
    build:
      context: ./backend
    container_name: cantinacf-backend
    hostname: cantinacf-backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    networks:
      - cantinacf
    environment:
      - TZ=America/Maceio

  cantinacf-frontend:
    build:
      context: ./frontend
    container_name: cantinacf-frontend
    hostname: cantinacf-frontend
    command:
      - sh
      - -c
      - |
        npm install && \
        npm run build && \
        npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://cantinacf-backend:5000
    networks:
      - cantinacf
    depends_on:
      - cantinacf-backend

networks:
  cantinacf:
    driver: bridge
    name: cantinacf-network

volumes:
  nginx_data:
    driver: local
